//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadingParameters
{
    using System;
    using System.Collections.Generic;
    
    public partial class vdp04
    {
        public Nullable<System.DateTime> dateandtime { get; set; }
        public Nullable<int> mks { get; set; }
        public string tagname { get; set; }
        public Nullable<double> val { get; set; }
        public int id { get; set; }
    }
}
